"""
WikiGenerator: Turns a RepoAnalysis into a set of named markdown pages.
Produces DeepWiki-parity output:
  - index.md           (overview, purpose, tech stack, nav)
  - architecture.md    (C4 diagram, architecture style, layers)
  - components/*.md    (per-service-group pages)
  - api-reference.md   (all HTTP endpoints)
  - data-models.md     (JPA entities + fields)
  - infrastructure.md  (Docker, K8s, CI/CD, env vars)
  - dependencies.md    (class dependency map, external deps)
"""
from dataclasses import dataclass
from typing import List, Dict, Any, Optional
from datetime import datetime

from analyzer.claude_client import RepoAnalysis


@dataclass
class WikiPage:
    filename: str        # relative to output dir, e.g. "components/user-service.md"
    title: str
    content: str


class WikiGenerator:
    def __init__(self, analysis: RepoAnalysis, repo_name: str):
        self.a = analysis
        self.repo_name = repo_name
        self.ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    def generate_all(self) -> List[WikiPage]:
        pages: List[WikiPage] = []
        pages.append(self._index_page())
        pages.append(self._architecture_page())
        pages.append(self._api_reference_page())
        pages.append(self._data_models_page())
        pages.append(self._infrastructure_page())
        pages.append(self._dependencies_page())
        # Per-service-group component pages
        for group in self.a.services:
            pages.append(self._component_page(group))
        return pages

    # ------------------------------------------------------------------ #
    #  index.md                                                            #
    # ------------------------------------------------------------------ #
    def _index_page(self) -> WikiPage:
        a = self.a

        # Tech stack badges
        badge_map = {
            "Spring Boot": "springboot-6DB33F?logo=springboot&logoColor=white",
            "Java": "java-ED8B00?logo=openjdk&logoColor=white",
            "Maven": "maven-C71A36?logo=apachemaven&logoColor=white",
            "Gradle": "gradle-02303A?logo=gradle&logoColor=white",
            "Docker": "docker-2496ED?logo=docker&logoColor=white",
            "Kubernetes": "kubernetes-326CE5?logo=kubernetes&logoColor=white",
            "Kafka": "kafka-231F20?logo=apachekafka&logoColor=white",
            "PostgreSQL": "postgresql-4169E1?logo=postgresql&logoColor=white",
            "MySQL": "mysql-4479A1?logo=mysql&logoColor=white",
            "Redis": "redis-DC382D?logo=redis&logoColor=white",
            "AWS": "aws-232F3E?logo=amazonaws&logoColor=white",
            "GitHub Actions": "githubactions-2088FF?logo=githubactions&logoColor=white",
        }
        badges = ""
        for tech in a.tech_stack:
            for name, badge in badge_map.items():
                if name.lower() in tech.lower():
                    badges += f"![{name}](https://img.shields.io/badge/{badge}) "
                    break
            else:
                safe = tech.replace(" ", "%20").replace("-", "--")
                badges += f"![{tech}](https://img.shields.io/badge/{safe}-555?style=flat) "

        # Service group table
        service_rows = ""
        for g in a.services:
            classes_preview = ", ".join(g.get("classes", [])[:4])
            if len(g.get("classes", [])) > 4:
                classes_preview += f", +{len(g['classes'])-4} more"
            service_rows += (
                f"| [{g.get('name','')}](components/{self._slug(g.get('name',''))}.md) "
                f"| {g.get('layer','')} "
                f"| {g.get('purpose','')} "
                f"| `{classes_preview}` |\n"
            )

        content = f"""# {a.repo_name}

> {a.system_purpose}

{badges}

---

## Quick Navigation

| Section | Description |
|---|---|
| [Architecture](architecture.md) | System diagram, layers, architecture style |
| [Components](components/) | Per-module deep-dives |
| [API Reference](api-reference.md) | All HTTP endpoints |
| [Data Models](data-models.md) | JPA entities and schemas |
| [Infrastructure](infrastructure.md) | Docker, K8s, CI/CD |
| [Dependencies](dependencies.md) | Internal and external dependencies |

---

## System Overview

**Architecture style:** `{a.architecture_style}`

{a.system_purpose}

### Tech Stack

{chr(10).join(f"- {t}" for t in a.tech_stack)}

---

## Service Groups

| Group | Layer | Purpose | Key Classes |
|---|---|---|---|
{service_rows}

---

## Stats

| Metric | Value |
|---|---|
| Java classes analysed | {len(a.modules)} |
| HTTP endpoints | {len(a.endpoints)} |
| JPA entities | {len(a.data_models)} |
| Service groups | {len(a.services)} |

---

*Generated by RepoWiki on {self.ts}*
"""
        return WikiPage("index.md", f"{a.repo_name} — Overview", content)

    # ------------------------------------------------------------------ #
    #  architecture.md                                                     #
    # ------------------------------------------------------------------ #
    def _architecture_page(self) -> WikiPage:
        a = self.a

        arch_diagram = f"""```mermaid
{a.mermaid_architecture}
```""" if a.mermaid_architecture else "_Diagram not generated._"

        comp_diagram = f"""```mermaid
{a.mermaid_components}
```""" if a.mermaid_components else "_Component diagram not generated._"

        seq_diagram = f"""```mermaid
{a.mermaid_sequence}
```""" if a.mermaid_sequence else "_Sequence diagram not generated._"

        # Layer breakdown table
        layers: Dict[str, List[str]] = {}
        for g in a.services:
            layer = g.get("layer", "unknown")
            layers.setdefault(layer, []).append(g.get("name", ""))
        layer_rows = "\n".join(
            f"| **{layer.title()}** | {', '.join(names)} |"
            for layer, names in layers.items()
        )

        content = f"""# Architecture — {a.repo_name}

## System Context Diagram

{arch_diagram}

---

## Architecture Style

**{a.architecture_style.title()}**

This application follows a **{a.architecture_style}** architectural style.

### Layers

| Layer | Components |
|---|---|
{layer_rows}

---

## Component Map

{comp_diagram}

---

## Primary Request Flow

{seq_diagram}

---

## Key Packages

{chr(10).join(f"- `{p}`" for p in a.key_packages)}

---

*[← Back to Index](index.md)*
"""
        return WikiPage("architecture.md", "Architecture", content)

    # ------------------------------------------------------------------ #
    #  api-reference.md                                                   #
    # ------------------------------------------------------------------ #
    def _api_reference_page(self) -> WikiPage:
        endpoints = self.a.endpoints
        if not endpoints:
            content = f"# API Reference — {self.repo_name}\n\n_No HTTP endpoints detected._\n\n*[← Back](index.md)*\n"
            return WikiPage("api-reference.md", "API Reference", content)

        # Group by class
        by_class: Dict[str, List] = {}
        for ep in endpoints:
            cls = ep.get("class", "Unknown")
            by_class.setdefault(cls, []).append(ep)

        sections = ""
        for cls, eps in sorted(by_class.items()):
            rows = ""
            for ep in eps:
                method = ep.get("method", "")
                badge = {
                    "GET": "![GET](https://img.shields.io/badge/GET-61affe?style=flat)",
                    "POST": "![POST](https://img.shields.io/badge/POST-49cc90?style=flat)",
                    "PUT": "![PUT](https://img.shields.io/badge/PUT-fca130?style=flat)",
                    "DELETE": "![DELETE](https://img.shields.io/badge/DELETE-f93e3e?style=flat)",
                    "PATCH": "![PATCH](https://img.shields.io/badge/PATCH-50e3c2?style=flat)",
                }.get(method, f"`{method}`")
                path = ep.get("path", "/")
                handler = ep.get("handler", "")
                desc = ep.get("description", "")
                rows += f"| {badge} | `{path}` | `{handler}` | {desc} |\n"

            sections += f"""### `{cls}`

| Method | Path | Handler | Description |
|---|---|---|---|
{rows}
"""

        content = f"""# API Reference — {self.repo_name}

> Auto-generated from `@GetMapping`, `@PostMapping`, `@PutMapping`, `@DeleteMapping`, `@PatchMapping` annotations.

**Total endpoints: {len(endpoints)}**

---

{sections}

---

*[← Back to Index](index.md)*
"""
        return WikiPage("api-reference.md", "API Reference", content)

    # ------------------------------------------------------------------ #
    #  data-models.md                                                      #
    # ------------------------------------------------------------------ #
    def _data_models_page(self) -> WikiPage:
        models = self.a.data_models
        if not models:
            content = f"# Data Models — {self.repo_name}\n\n_No JPA entities detected._\n\n*[← Back](index.md)*\n"
            return WikiPage("data-models.md", "Data Models", content)

        sections = ""
        for m in models:
            cls = m.get("class", "Unknown")
            pkg = m.get("package", "")
            fields = m.get("fields", [])
            rows = "\n".join(
                f"| `{f.get('name','')}` | `{f.get('type','')}` |"
                for f in fields
            ) or "| — | — |"
            sections += f"""### `{cls}`
> Package: `{pkg}`

| Field | Type |
|---|---|
{rows}

"""

        # Entity relationship diagram attempt
        erd_lines = []
        for m in models:
            cls = m.get("class", "Unknown")
            for f in m.get("fields", []):
                ftype = f.get("type", "")
                # If field type matches another entity name
                if any(ftype == other.get("class") for other in models if other.get("class") != cls):
                    erd_lines.append(f"  {cls} ||--o{{ {ftype} : has")
        erd = ""
        if erd_lines:
            erd = "## Entity Relationships\n\n```mermaid\nerDiagram\n" + "\n".join(erd_lines) + "\n```\n\n---\n\n"

        content = f"""# Data Models — {self.repo_name}

{erd}## Entities

{sections}

---

*[← Back to Index](index.md)*
"""
        return WikiPage("data-models.md", "Data Models", content)

    # ------------------------------------------------------------------ #
    #  infrastructure.md                                                  #
    # ------------------------------------------------------------------ #
    def _infrastructure_page(self) -> WikiPage:
        infra = self.a.infra_summary

        services_rows = ""
        for svc in infra.get("services", []):
            services_rows += (
                f"| `{svc.get('name','')}` | `{svc.get('image','')}` | {svc.get('purpose','')} |\n"
            )

        env_vars = "\n".join(f"- `{e}`" for e in infra.get("environment_variables", []))
        databases = "\n".join(f"- {d}" for d in infra.get("databases", []))
        brokers = "\n".join(f"- {b}" for b in infra.get("message_brokers", []))
        ports = ", ".join(f"`{p}`" for p in infra.get("exposed_ports", []))

        content = f"""# Infrastructure — {self.repo_name}

## Overview

| Property | Value |
|---|---|
| Containerized | {infra.get('containerized', 'unknown')} |
| Orchestration | {infra.get('orchestration', 'unknown')} |
| Cloud Provider | {infra.get('cloud_provider', 'unknown')} |
| CI/CD | {infra.get('ci_cd', 'unknown')} |
| Exposed Ports | {ports or '—'} |

---

## Services

| Service | Image | Purpose |
|---|---|---|
{services_rows or "| — | — | — |"}

---

## Databases

{databases or "_None detected._"}

## Message Brokers

{brokers or "_None detected._"}

## Environment Variables

{env_vars or "_None detected._"}

---

*[← Back to Index](index.md)*
"""
        return WikiPage("infrastructure.md", "Infrastructure", content)

    # ------------------------------------------------------------------ #
    #  dependencies.md                                                    #
    # ------------------------------------------------------------------ #
    def _dependencies_page(self) -> WikiPage:
        dep_map = self.a.dependencies

        rows = ""
        for cls, deps in sorted(dep_map.items()):
            if deps:
                rows += f"| `{cls}` | {', '.join(f'`{d}`' for d in deps)} |\n"

        # Mermaid dep graph (top 20 edges)
        edges = []
        for cls, deps in sorted(dep_map.items()):
            for d in deps[:3]:
                safe_cls = cls.replace(" ", "_")
                safe_d = d.replace(" ", "_")
                edges.append(f"  {safe_cls} --> {safe_d}")
        dep_mermaid = ""
        if edges:
            dep_mermaid = "## Dependency Graph\n\n```mermaid\ngraph LR\n" + \
                "\n".join(edges[:30]) + "\n```\n\n---\n\n"

        content = f"""# Dependencies — {self.repo_name}

{dep_mermaid}## Class Dependency Table

| Class | Depends On |
|---|---|
{rows or "| — | — |"}

---

*[← Back to Index](index.md)*
"""
        return WikiPage("dependencies.md", "Dependencies", content)

    # ------------------------------------------------------------------ #
    #  components/<group>.md                                              #
    # ------------------------------------------------------------------ #
    def _component_page(self, group: Dict) -> WikiPage:
        name = group.get("name", "Unknown")
        slug = self._slug(name)
        layer = group.get("layer", "unknown")
        purpose = group.get("purpose", "")
        classes = group.get("classes", [])
        ext_deps = group.get("external_dependencies", [])
        key_apis = group.get("key_apis", [])

        # Find module details for each class
        class_details = ""
        for cls in classes:
            module = next((m for m in self.a.modules if m.get("_class") == cls), None)
            if module:
                resps = "\n".join(f"  - {r}" for r in module.get("responsibilities", [])[:5])
                patterns = ", ".join(module.get("notable_patterns", []))
                endpoints = module.get("endpoints", [])
                ep_rows = "\n".join(
                    f"  - `{ep.get('method','')} {ep.get('path','')}` — {ep.get('description','')}"
                    for ep in endpoints[:5]
                )
                class_details += f"""
#### `{cls}`

> **Role:** {module.get('_role', '')}  
> **Complexity:** {module.get('complexity', '')}  
> **Path:** `{module.get('_path', '')}`

{resps or '  _No responsibilities extracted._'}

"""
                if patterns:
                    class_details += f"**Patterns:** {patterns}\n\n"
                if ep_rows:
                    class_details += f"**Endpoints:**\n{ep_rows}\n\n"

        content = f"""# {name}

> **Layer:** `{layer}` | [← Back to Index](../index.md)

## Purpose

{purpose}

---

## Classes in this Group

{class_details or '_No class details available._'}

---

## External Dependencies

{chr(10).join(f'- {d}' for d in ext_deps) or '_None detected._'}

## Key APIs Exposed

{chr(10).join(f'- {a}' for a in key_apis) or '_None detected._'}

---

*[← Back to Index](../index.md) · [Architecture](../architecture.md)*
"""
        return WikiPage(f"components/{slug}.md", name, content)

    def _slug(self, name: str) -> str:
        return name.lower().replace(" ", "-").replace("/", "-").replace("_", "-")
